import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header"; 
import WhatsAppChat from "@/components/WhatsAppChat"; // ✅ import chat button

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* <Header /> */}
        {children}
        <WhatsAppChat
        // phone="+2348012345678"           
        welcome="Hi! I’m brethren ✝️  — I welcome you in the name of JESUS.
        How may i help you today ?"
        ctaText="Chat on WhatsApp"
        // presetText="Hello! I’d like to speak with support."
      />
      </body>
    </html>
  );
}
